# Runs the Ruff linter and formatter.

name: Lint

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
